export const metroAreas = [
  "New York-Newark-Jersey City, NY-NJ-PA MSA",
  "Los Angeles-Long Beach-Anaheim, CA MSA",
  "Chicago-Naperville-Elgin, IL-IN-WI MSA",
  "Dallas-Fort Worth-Arlington, TX MSA",
  "Houston-The Woodlands-Sugar Land, TX MSA",
  "Washington-Arlington-Alexandria, DC-VA-MD-WV MSA",
  "Philadelphia-Camden-Wilmington, PA-NJ-DE-MD MSA",
  "Atlanta-Sandy Springs-Alpharetta, GA MSA",
  "Miami-Fort Lauderdale-Pompano Beach, FL MSA",
  "Phoenix-Mesa-Chandler, AZ MSA",
  "Boston-Cambridge-Newton, MA-NH MSA",
  "Riverside-San Bernardino-Ontario, CA MSA",
  "San Francisco-Oakland-Berkeley, CA MSA",
  "Detroit–Warren–Dearborn, MI MSA",
  "Seattle-Tacoma-Bellevue, WA MSA",
  "Minneapolis-St. Paul-Bloomington, MN-WI MSA",
  "Tampa-St. Petersburg-Clearwater, FL MSA",
  "San Diego-Chula Vista-Carlsbad, CA MSA",
  "Denver-Aurora-Lakewood, CO MSA",
  "Baltimore-Columbia-Towson, MD MSA",
  "St. Louis, MO-IL MSA",
  "Orlando-Kissimmee-Sanford, FL MSA",
  "Charlotte-Concord-Gastonia, NC-SC MSA",
  "San Antonio-New Braunfels, TX MSA",
  "Portland-Vancouver-Hillsboro, OR-WA MSA",
  "Austin-Round Rock-Georgetown, TX MSA",
  "Sacramento-Roseville-Folsom, CA MSA",
  "Pittsburgh, PA MSA",
  "Las Vegas-Henderson-Paradise, NV MSA",
  "Cincinnati, OH-KY-IN MSA",
  "Kansas City, MO-KS MSA",
  "Columbus, OH MSA",
  "Indianapolis-Carmel-Anderson, IN MSA",
  "Cleveland-Elyria, OH MSA",
  "Nashville-Davidson–Murfreesboro–Franklin, TN MSA",
  "San Jose-Sunnyvale-Santa Clara, CA MSA",
  "Virginia Beach-Norfolk-Newport News, VA-NC MSA",
  "Jacksonville, FL MSA",
  "Providence-Warwick, RI-MA MSA",
  "Milwaukee-Waukesha, WI MSA",
  "Raleigh-Cary, NC MSA",
  "Oklahoma City, OK MSA",
  "Richmond, VA MSA",
  "Memphis, TN-MS-AR MSA",
  "Louisville/Jefferson County, KY-IN MSA",
  "Salt Lake City, UT MSA",
  "New Orleans-Metairie, LA MSA",
  "Hartford-East Hartford-Middletown, CT MSA",
  "Buffalo-Cheektowaga, NY MSA",
  "Birmingham-Hoover, AL MSA",
  "Grand Rapids-Kentwood, MI MSA",
  "Rochester, NY MSA",
  "Tucson, AZ MSA",
  "Tulsa, OK MSA",
  "Fresno, CA MSA",
  "Urban Honolulu, HI MSA",
  "Worcester, MA-CT MSA",
  "Omaha-Council Bluffs, NE-IA MSA",
  "Bridgeport-Stamford-Norwalk, CT MSA",
  "Greenville-Anderson, SC MSA",
  "Albuquerque, NM MSA",
  "Bakersfield, CA MSA",
  "Knoxville, TN MSA",
  "Albany-Schenectady-Troy, NY MSA",
  "North Port-Sarasota-Bradenton, FL MSA",
  "McAllen-Edinburg-Mission, TX MSA",
  "Baton Rouge, LA MSA",
  "El Paso, TX MSA",
  "Allentown-Bethlehem-Easton, PA-NJ MSA",
  "New Haven-Milford, CT MSA",
  "Columbia, SC MSA",
  "Oxnard-Thousand Oaks-Ventura, CA MSA",
  "Charleston-North Charleston, SC MSA",
  "Cape Coral-Fort Myers, FL MSA",
  "Dayton-Kettering, OH MSA",
  "Boise, ID MSA",
  "Stockton, CA MSA",
  "Lakeland-Winter Haven, FL MSA",
  "Greensboro-High Point, NC MSA",
  "Colorado Springs, CO MSA",
  "Little Rock-North Little Rock-Conway, AR MSA",
  "Des Moines-West Des Moines, IA MSA",
  "Provo-Orem, UT MSA",
  "Ogden-Clearfield, UT MSA",
  "Deltona-Daytona Beach-Ormond Beach, FL MSA",
  "Poughkeepsie-Newburgh-Middletown, NY MSA",
  "Akron, OH MSA",
  "Springfield, MA MSA",
  "Winston-Salem, NC MSA",
  "Madison, WI MSA",
  "Durham-Chapel Hill, NC MSA",
  "Syracuse, NY MSA",
  "Wichita, KS MSA",
  "Toledo, OH MSA",
  "Palm Bay-Melbourne-Titusville, FL MSA",
  "Augusta-Richmond County, GA-SC MSA",
  "Harrisburg-Carlisle, PA MSA",
  "Spokane-Spokane Valley, WA MSA",
  "Jackson, MS MSA",
  "Fayetteville-Springdale-Rogers, AR MSA",
  "Chattanooga, TN-GA MSA",
  "Scranton–Wilkes-Barre, PA MSA",
  "Portland-South Portland, ME MSA",
  "Lancaster, PA MSA",
  "Modesto, CA MSA",
  "Lansing-East Lansing, MI MSA",
  "Myrtle Beach-Conway-North Myrtle Beach, SC-NC MSA",
  "Youngstown-Warren-Boardman, OH-PA MSA",
  "Fayetteville, NC MSA",
  "Pensacola-Ferry Pass-Brent, FL MSA",
  "Port St. Lucie, FL MSA",
  "Lexington-Fayette, KY MSA",
  "Huntsville, AL MSA",
  "Reno, NV MSA",
  "Killeen-Temple, TX MSA",
  "Springfield, MO MSA",
  "Santa Rosa-Petaluma, CA MSA",
  "Lafayette, LA MSA",
  "Visalia, CA MSA",
  "Asheville, NC MSA",
  "York-Hanover, PA MSA",
  "Vallejo, CA MSA",
  "Santa Maria-Santa Barbara, CA MSA",
  "Salisbury, MD-DE MSA",
  "Salem, OR MSA",
  "Salinas, CA MSA",
  "Reading, PA MSA",
  "Manchester-Nashua, NH MSA",
  "Mobile, AL MSA",
  "Fort Wayne, IN MSA",
  "Brownsville-Harlingen, TX MSA",
  "Corpus Christi, TX MSA",
  "Gulfport-Biloxi, MS MSA",
  "Savannah, GA MSA",
  "Flint, MI MSA",
  "Anchorage, AK MSA",
  "Canton-Massillon, OH MSA",
  "Naples-Marco Island, FL MSA",
  "Peoria, IL MSA",
  "Ocala, FL MSA",
  "Beaumont-Port Arthur, TX MSA",
  "Tallahassee, FL MSA",
  "Montgomery, AL MSA",
  "Shreveport-Bossier City, LA MSA",
  "Eugene-Springfield, OR MSA",
  "Trenton-Princeton, NJ MSA",
  "Davenport-Moline-Rock Island, IA-IL MSA",
  "Hickory-Lenoir-Morganton, NC MSA",
  "Fort Collins, CO MSA",
  "Ann Arbor, MI MSA",
  "Huntington-Ashland, WV-KY-OH MSA",
  "Greeley, CO MSA",
  "Gainesville, FL MSA",
  "Spartanburg, SC MSA",
  "Lincoln, NE MSA",
  "Clarksville, TN-KY MSA",
  "Rockford, IL MSA",
  "Green Bay, WI MSA",
  "Lubbock, TX MSA",
  "Boulder, CO MSA",
  "Columbus, GA-AL MSA",
  "South Bend-Mishawaka, IN-MI MSA",
  "Roanoke, VA MSA",
  "Evansville, IN-KY MSA",
  "Kennewick-Richland, WA MSA",
  "Kingsport-Bristol, TN-VA MSA",
  "Hagerstown-Martinsburg, MD-WV MSA",
  "Wilmington, NC MSA",
  "Crestview-Fort Walton Beach-Destin, FL MSA",
  "Olympia-Lacey-Tumwater, WA MSA",
  "Duluth, MN-WI MSA",
  "Longview, TX MSA",
  "Merced, CA MSA",
  "Sioux Falls, SD MSA",
  "Utica-Rome, NY MSA",
  "Waco, TX MSA",
  "San Luis Obispo-Paso Robles, CA MSA",
  "College Station-Bryan, TX MSA",
  "Bremerton-Silverdale-Port Orchard, WA MSA",
  "Tuscaloosa, AL MSA",
  "Atlantic City-Hammonton, NJ MSA",
  "Cedar Rapids, IA MSA",
  "Amarillo, TX MSA",
  "Norwich-New London, CT MSA",
  "Laredo, TX MSA",
  "Erie, PA MSA",
  "Santa Cruz-Watsonville, CA MSA",
  "Lynchburg, VA MSA",
  "Kalamazoo-Portage, MI MSA",
  "Fargo, ND-MN MSA",
  "Yakima, WA MSA",
  "Charleston, WV MSA",
  "Fort Smith, AR-OK MSA",
  "Daphne-Fairhope-Foley, AL MSA",
  "Prescott Valley-Prescott, AZ MSA",
  "Binghamton, NY MSA",
  "Appleton, WI MSA",
  "Tyler, TX MSA",
  "Macon-Bibb County, GA MSA",
  "Barnstable Town, MA MSA",
  "Topeka, KS MSA",
  "Bellingham, WA MSA",
  "Hilton Head Island-Bluffton, SC MSA",
  "Rochester, MN MSA",
  "Burlington-South Burlington, VT MSA",
  "Lafayette-West Lafayette, IN MSA",
  "Charlottesville, VA MSA",
  "Las Cruces, NM MSA",
  "Champaign-Urbana, IL MSA",
  "Medford, OR MSA",
  "Lake Havasu City-Kingman, AZ MSA",
  "Athens-Clarke County, GA MSA",
  "Columbia, MO MSA",
  "Gainesville, GA MSA",
  "Johnson City, TN MSA",
  "Yuma, AZ MSA",
  "Lake Charles, LA MSA",
  "Chico, CA MSA",
  "Jacksonville, NC MSA",
  "Elkhart-Goshen, IN MSA",
  "Springfield, IL MSA",
  "Bend, OR MSA",
  "Monroe, LA MSA",
  "Punta Gorda, FL MSA",
  "St. Cloud, MN MSA",
  "Houma-Thibodaux, LA MSA",
  "Florence, SC MSA",
  "Warner Robins, GA MSA",
  "St. George, UT MSA",
  "Racine, WI MSA",
  "Billings, MT MSA",
  "Saginaw, MI MSA",
  "Dover, DE MSA",
  "Bowling Green, KY MSA",
  "Panama City, FL MSA",
  "Terre Haute, IN MSA",
  "Joplin, MO MSA",
  "Coeur d'Alene, ID MSA",
  "Yuba City, CA MSA",
  "Kingston, NY MSA",
  "Jackson, TN MSA",
  "Redding, CA MSA",
  "Auburn-Opelika, AL MSA",
  "Abilene, TX MSA",
  "Iowa City, IA MSA",
  "El Centro, CA MSA",
  "Midland, TX MSA",
  "Muskegon, MI MSA",
  "Burlington, NC MSA",
  "Eau Claire, WI MSA",
  "Greenville, NC MSA",
  "Hattiesburg, MS MSA",
  "Bloomington, IL MSA",
  "Oshkosh-Neenah, WI MSA",
  "Pueblo, CO MSA",
  "Waterloo-Cedar Falls, IA MSA",
  "Sebastian-Vero Beach, FL MSA",
  "East Stroudsburg, PA MSA",
  "Wausau-Weston, WI MSA",
  "Blacksburg-Christiansburg, VA MSA",
  "Idaho Falls, ID MSA",
  "Kahului-Wailuku-Lahaina, HI MSA",
  "Janesville-Beloit, WI MSA",
  "Homosassa Springs, FL MSA",
  "Bloomington, IN MSA",
  "Odessa, TX MSA",
  "Madera, CA MSA",
  "Jackson, MI MSA",
  "Grand Junction, CO MSA",
  "State College, PA MSA",
  "Decatur, AL MSA",
  "Elizabethtown-Fort Knox, KY MSA",
  "Chambersburg-Waynesboro, PA MSA",
  "Santa Fe, NM MSA",
  "Monroe, MI MSA",
  "Logan, UT-ID MSA",
  "Florence-Muscle Shoals, AL MSA",
  "Bangor, ME MSA",
  "Hanford-Corcoran, CA MSA",
  "Niles, MI MSA",
  "Dothan, AL MSA",
  "Vineland-Bridgeton, NJ MSA",
  "Jefferson City, MO MSA",
  "Valdosta, GA MSA",
  "Wichita Falls, TX MSA",
  "Sioux City, IA-NE-SD MSA",
  "Alexandria, LA MSA",
  "Winchester, VA-WV MSA",
  "Texarkana, TX-AR MSA",
  "Morristown, TN MSA",
  "Albany, GA MSA",
  "Rapid City, SD MSA",
  "The Villages, FL MSA",
  "Rocky Mount, NC MSA",
  "Flagstaff, AZ MSA",
  "Lebanon, PA MSA",
  "Dalton, GA MSA",
  "Sherman-Denison, TX MSA",
  "Morgantown, WV MSA",
  "La Crosse-Onalaska, WI-MN MSA",
  "Hammond, LA MSA",
  "Wheeling, WV-OH MSA",
  "Harrisonburg, VA MSA",
  "Jonesboro, AR MSA",
  "Sumter, SC MSA",
  "Bismarck, ND MSA",
  "Springfield, OH MSA",
  "Napa, CA MSA",
  "Battle Creek, MI MSA",
  "Manhattan, KS MSA",
  "Carbondale-Marion, IL MSA",
  "Johnstown, PA MSA",
  "Mount Vernon-Anacortes, WA MSA",
  "Albany-Lebanon, OR MSA",
  "Lawton, OK MSA",
  "Cleveland, TN MSA",
  "Pittsfield, MA MSA",
  "Staunton, VA MSA",
  "Glens Falls, NY MSA",
  "Ames, IA MSA",
  "Sierra Vista-Douglas, AZ MSA",
  "Mansfield, OH MSA",
  "Wenatchee, WA MSA",
  "New Bern, NC MSA",
  "San Angelo, TX MSA",
  "Owensboro, KY MSA",
  "Missoula, MT MSA",
  "Altoona, PA MSA",
  "Farmington, NM MSA",
  "Lawrence, KS MSA",
  "St. Joseph, MO-KS MSA",
  "Twin Falls, ID MSA",
  "Sheboygan, WI MSA",
  "Goldsboro, NC MSA",
  "Watertown-Fort Drum, NY MSA",
  "Anniston-Oxford, AL MSA",
  "California-Lexington Park, MD MSA",
  "Brunswick, GA MSA",
  "Weirton-Steubenville, WV-OH MSA",
  "Williamsport, PA MSA",
  "Lewiston-Auburn, ME MSA",
  "Beckley, WV MSA",
  "Muncie, IN MSA",
  "Longview, WA MSA",
  "Michigan City-La Porte, IN MSA",
  "Kankakee, IL MSA",
  "Gettysburg, PA MSA",
  "Sebring-Avon Park, FL MSA",
  "Ithaca, NY MSA",
  "Mankato, MN MSA",
  "Fond du Lac, WI MSA",
  "Grand Forks, ND-MN MSA",
  "Gadsden, AL MSA",
  "Bay City, MI MSA",
  "Decatur, IL MSA",
  "Lima, OH MSA",
  "Cheyenne, WY MSA",
  "Hot Springs, AR MSA",
  "Rome, GA MSA",
  "Dubuque, IA MSA",
  "Cape Girardeau, MO-IL MSA",
  "Victoria, TX MSA",
  "Corvallis, OR MSA",
  "Pocatello, ID MSA",
  "Ocean City, NJ MSA",
  "Fairbanks, AK MSA",
  "Cumberland, MD-WV MSA",
  "Parkersburg-Vienna, WV MSA",
  "Grants Pass, OR MSA",
  "Hinesville, GA MSA",
  "Great Falls, MT MSA",
  "Pine Bluff, AR MSA",
  "Midland, MI MSA",
  "Kokomo, IN MSA",
  "Columbus, IN MSA",
  "Bloomsburg-Berwick, PA MSA",
  "Elmira, NY MSA",
  "Casper, WY MSA",
  "Grand Island, NE MSA",
  "Danville, IL MSA",
  "Lewiston, ID-WA MSA",
  "Enid, OK MSA",
  "Walla Walla, WA MSA",
  "Carson City, NV MSA"
]